kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-user
  namespace: production
subjects:
- kind: User
  name: my-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: my-user
  apiGroup: rbac.authorization.k8s.io
