apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: production  
spec:
  selector:
    app: node-app  
  ports:
    - protocol: TCP
      port: 8000      
      targetPort: 8000
  type: LoadBalancer
